export enum MileageStatuses {
    REALISTIC = 'REALISTIC',
    ROLLED_BACK = 'ROLLED_BACK',
    BELOW_AVERAGE = 'BELOW_AVERAGE',
    HEAVY_USAGE = 'HEAVY_USAGE',
    SUSPICIOUSLY_HIGH = 'SUSPICIOUSLY_HIGH',
};